{{- if eq .Values.global.registry_location "on-cluster" }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: deis-registry-proxy
  labels:
    heritage: deis
  annotations:
    component.deis.io/version: {{ .Values.docker_tag }}
spec:
  selector:
    matchLabels:
      app: deis-registry-proxy
      heritage: deis
  template:
    metadata:
      name: deis-registry-proxy
      labels:
        heritage: deis
        app: deis-registry-proxy
    spec:
{{- if (.Values.global.use_cni) }}
      hostNetwork: true
{{- end}}
      containers:
      - name: deis-registry-proxy
        image: quay.io/{{.Values.org}}/registry-proxy:{{.Values.docker_tag}}
        imagePullPolicy: {{.Values.pull_policy}}
{{- if or (.Values.limits_cpu) (.Values.limits_memory)}}
        resources:
          limits:
{{- if (.Values.limits_cpu) }}
            cpu: {{.Values.limits_cpu}}
{{- end}}
{{- if (.Values.limits_memory) }}
            memory: {{.Values.limits_memory}}
{{- end}}
{{- end}}
        env:
        - name: REGISTRY_HOST
          value: $(DEIS_REGISTRY_SERVICE_HOST)
        - name: REGISTRY_PORT
          value: $(DEIS_REGISTRY_SERVICE_PORT)
        - name: BIND_ADDR
{{- if (.Values.global.use_cni) }}
          value: {{ default "127.0.0.1:5555" .Values.global.registry_proxy_bind_addr | quote }}
{{- else }}
          value: {{ default "80" .Values.global.registry_proxy_bind_addr | quote }}
{{- end }}
{{- if not (.Values.global.use_cni) }}
        ports:
        - containerPort: 80
          hostPort: {{.Values.global.host_port}}
{{- end }}
{{- end }}
